# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'LTCycleView' do
pod 'Kingfisher', '~> 3.1.1'
end